export const FETCH_RECIPE = "FETCH_RECIPE";
export const FETCH_RECIPE_LIST = "FETCH_RECIPE_LIST";
export const FETCH_SCHEDULE_ITEM = "FETCH_SCHEDULE_ITEM";
export const FETCH_SCHEDULE_ITEM_LIST = "FETCH_SCHEDULE_ITEM_LIST";
export const FETCH_TODOS = "FETCH_TODOS";
export const FETCH_USER = "FETCH_USER";
